### ISSUE TITLE
newarticle.sh says dependency is satisfied, even when it is not

### ISSUE THREAD

**Issue by erazemkokot** [AnarchyLinux/website#2]
I tried running the `newarticle.sh` script, which prompted me to install `pandoc`.

Since I'm on Fedora `pacman` obviously wasn't installed, but the script still continued, with the text "Dependencies satisfied":

```
Do you want to create a new article? [y/N] y

Missing dependencies:  pandoc 

Install missing dependencies now? [y/N]: y
[sudo] password for ekokot: 
sudo: pacman: command not found
Dependencies satisfied!

Select one of the following tags [1|2]:

1. Releases
2. News
?> ^C
```

The `^C` is me pressing Ctrl+C

**Comment by PandaFoss** [comment]
Check if it was fixed.

**Comment by erazemkokot** [comment]
Should work fine.
